version: '3.8'
services:
  web:
    build:
      context: ./
    container_name: ecommerce-web
    restart: always
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - '9090:9090'
    environment:
      NODE_ENV: dev
      PORT: 9090
      DEBUG: nodejs-docker-express:*
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13.4
    container_name: ecommerce-db
    restart: always
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=ecommerce-user
      - POSTGRES_PASSWORD=RAnoP5244X9Aen5w8U6CKQ
    ports:
      - '5440:5432'
    volumes:
      - ~/postgres/ecommerce:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
